#!/bin/bash
# nodejs
sudo pacman -S  --color never community/nodejs
# mongodb
sudo pacman -S  --color never community/mongodb
sudo systemctl enable mongodb.service
sudo mkdir /data /data/db
sudo chmod -R 777 /data
# bower
sudo npm install -g bower
# Grunt
sudo npm install -g grunt-cli
# Yo and the qui-va-bien generator
sudo npm install -g yo
sudo npm install -g generator-meanjs
# SASS
yaourt -S  --nocolor aur/ruby-sass
npm install grunt-contrib-sass --save
npm install grunt-contrib-concat
npm install ruby-sass --save-dev

export PATH=$PATH:~/.gem/ruby/2.2.0/bin

cd app
npm install
